id: I6FB3A337
default_language: bo
source: ''
initial_creation_type: tmx
imported: 2022-12-14 14:33:37.666940+00:00
last_modified: 2022-12-14 14:33:37.666949+00:00
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-048-003
  eft-text-version: 1.0.10 2021
  title: Toh_103-The_Teaching_by_the_Child_Inconceivable_Radiance-v2
bases:
  A490:
    source_metadata: null
    order: 1
    base_file: A490.txt
    statistics: null
copyright:
  status: Unknown
  notice: ''
